/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Base_de_Datos.ConsultarDatos;
import Base_de_Datos.IngresarDatos;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author neox
 */
public class gestion_sedes extends javax.swing.JFrame {
    Sede sedePrincipal;
    ConsultarDatos consultasBD;
    IngresarDatos ingresosBD;
    
    private menu menu;
    
    private Listar_sedes listaSedes;
    /**
     * Creates new form gestion_sedes
     */
    public gestion_sedes(menu menu) {
        initComponents();
        sedePrincipal = new Sede();
        consultasBD = new ConsultarDatos();
        ingresosBD = new IngresarDatos();
        
        
        listaSedes = new Listar_sedes(this);
        this.menu = menu;
        
        nombreSede_jTextField.setEnabled(false);
        direccionSede_jTextField.setEnabled(false);
        telefonoSede_jTextField.setEnabled(false);
        estadoSede_jComboBox.setEnabled(false);
        correoSede_jTextField.setEnabled(false);
        ciudadSede_jTextField.setEnabled(false);
        IdSede_jTextField.setEnabled(false);
        
        crearSede_jButton.setEnabled(false);
        cancelarSede_jButton.setEnabled(false);
        limpiarSede_jButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info_jPanel = new javax.swing.JPanel();
        icono_jLabel = new javax.swing.JLabel();
        sedes_jLabel = new javax.swing.JLabel();
        ppal_jPanel = new javax.swing.JPanel();
        salir_jButton = new javax.swing.JButton();
        menu_jButton = new javax.swing.JButton();
        opcionSedes_jPanel = new javax.swing.JPanel();
        agregar_jButton = new javax.swing.JButton();
        modificar_jButton = new javax.swing.JButton();
        listar_jButton = new javax.swing.JButton();
        gestion_jPanel = new javax.swing.JPanel();

        nombreSede_jLabel = new javax.swing.JLabel();
        nombreSede_jTextField = new javax.swing.JTextField();
        nombreSede_jTextField.setEditable(false);
        direccionSede_jLabel = new javax.swing.JLabel();
        direccionSede_jTextField = new javax.swing.JTextField();
        direccionSede_jTextField.setEditable(false);
        telefonoSede_jLabel = new javax.swing.JLabel();
        telefonoSede_jTextField = new javax.swing.JTextField();
        EstadoSede_jLabel = new javax.swing.JLabel();
        correoSede_jLabel = new javax.swing.JLabel();
        correoSede_jTextField = new javax.swing.JTextField();
        ciudadSede_jLabel = new javax.swing.JLabel();
        ciudadSede_jTextField = new javax.swing.JTextField();
        estadoSede_jComboBox = new javax.swing.JComboBox();
        IdSede_jLabel = new javax.swing.JLabel();
        IdSede_jTextField = new javax.swing.JTextField();
        iconoSedes_jLabel = new javax.swing.JLabel();
        crearSede_jButton = new javax.swing.JButton();
        cancelarSede_jButton = new javax.swing.JButton();
        limpiarSede_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(698, 432));

        icono_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icono.png"))); // NOI18N
        icono_jLabel.setText("jLabel1");

        sedes_jLabel.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        sedes_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sedes_jLabel.setText("Módulo de gestión de sedes");

        javax.swing.GroupLayout info_jPanelLayout = new javax.swing.GroupLayout(info_jPanel);
        info_jPanel.setLayout(info_jPanelLayout);
        info_jPanelLayout.setHorizontalGroup(
            info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(info_jPanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(sedes_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        info_jPanelLayout.setVerticalGroup(
            info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(icono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(info_jPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sedes_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        salir_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/16-em-cross.png"))); // NOI18N
        salir_jButton.setText("Salir");
        salir_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_jButtonActionPerformed(evt);
            }
        });

        menu_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-frame.png"))); // NOI18N
        menu_jButton.setText("Menú");
        menu_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppal_jPanelLayout = new javax.swing.GroupLayout(ppal_jPanel);
        ppal_jPanel.setLayout(ppal_jPanelLayout);
        ppal_jPanelLayout.setHorizontalGroup(
            ppal_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppal_jPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(menu_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir_jButton))
        );
        ppal_jPanelLayout.setVerticalGroup(
            ppal_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppal_jPanelLayout.createSequentialGroup()
                .addGroup(ppal_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir_jButton)
                    .addComponent(menu_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        agregar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-image-add.png"))); // NOI18N
        agregar_jButton.setText("Agregar");
        agregar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_jButtonActionPerformed(evt);
            }
        });

        modificar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-image-open.png"))); // NOI18N
        modificar_jButton.setText("Modificar");
        modificar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_jButtonActionPerformed(evt);
            }
        });

        listar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-sidebar.png"))); // NOI18N
        listar_jButton.setText("Listar");
        listar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionSedes_jPanelLayout = new javax.swing.GroupLayout(opcionSedes_jPanel);
        opcionSedes_jPanel.setLayout(opcionSedes_jPanelLayout);
        opcionSedes_jPanelLayout.setHorizontalGroup(
            opcionSedes_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionSedes_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listar_jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionSedes_jPanelLayout.setVerticalGroup(
            opcionSedes_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionSedes_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(modificar_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(opcionSedes_jPanelLayout.createSequentialGroup()
                .addComponent(listar_jButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gestion_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Sede"));

        nombreSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        nombreSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreSede_jLabel.setText("Nombre*");

        nombreSede_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSede_jTextFieldActionPerformed(evt);
            }
        });

        direccionSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        direccionSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        direccionSede_jLabel.setText("Dirección*");

        telefonoSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        telefonoSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telefonoSede_jLabel.setText("Telefono*");

        telefonoSede_jTextField.setEditable(false);

        EstadoSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        EstadoSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EstadoSede_jLabel.setText("Estado*");

        correoSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        correoSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        correoSede_jLabel.setText("Correo*");

        correoSede_jTextField.setEditable(false);

        ciudadSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        ciudadSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ciudadSede_jLabel.setText("Ciudad");

        ciudadSede_jTextField.setEditable(false);
        ciudadSede_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadSede_jTextFieldActionPerformed(evt);
            }
        });

        estadoSede_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Activa", "Inactiva" }));
        estadoSede_jComboBox.setEnabled(false);
        estadoSede_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoSede_jComboBoxActionPerformed(evt);
            }
        });

        IdSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        IdSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IdSede_jLabel.setText("ID-Sede");

        IdSede_jTextField.setEditable(false);
        IdSede_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdSede_jTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gestion_jPanelLayout = new javax.swing.GroupLayout(gestion_jPanel);
        gestion_jPanel.setLayout(gestion_jPanelLayout);
        gestion_jPanelLayout.setHorizontalGroup(
            gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestion_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(nombreSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(direccionSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(telefonoSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(EstadoSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoSede_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(correoSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(ciudadSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ciudadSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(IdSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        gestion_jPanelLayout.setVerticalGroup(
            gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestion_jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreSede_jLabel)
                    .addComponent(nombreSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionSede_jLabel)
                    .addComponent(direccionSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoSede_jLabel)
                    .addComponent(telefonoSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoSede_jLabel)
                    .addComponent(estadoSede_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoSede_jLabel)
                    .addComponent(correoSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadSede_jLabel)
                    .addComponent(ciudadSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdSede_jLabel)
                    .addComponent(IdSede_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        iconoSedes_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/sedes.jpg"))); // NOI18N

        crearSede_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/16-em-check.png"))); // NOI18N
        crearSede_jButton.setText("Aceptar");
        crearSede_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSede_jButtonActionPerformed(evt);
            }
        });

        cancelarSede_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/12-em-cross.png"))); // NOI18N
        cancelarSede_jButton.setText("Cancelar");
        cancelarSede_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarSede_jButtonActionPerformed(evt);
            }
        });

        limpiarSede_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/16-broom_opt.png"))); // NOI18N
        limpiarSede_jButton.setText("Limpiar");
        limpiarSede_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarSede_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opcionSedes_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ppal_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(gestion_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iconoSedes_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearSede_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelarSede_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(limpiarSede_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ppal_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionSedes_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gestion_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(iconoSedes_jLabel)
                        .addGap(18, 18, 18)
                        .addComponent(crearSede_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarSede_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiarSede_jButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jButtonActionPerformed
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_jButtonActionPerformed

    private void salir_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_jButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_jButtonActionPerformed

    private void agregar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_jButtonActionPerformed
        nombreSede_jTextField.setEditable(true);
        direccionSede_jTextField.setEnabled(true);
        telefonoSede_jTextField.setEnabled(true);
        estadoSede_jComboBox.setEnabled(true);
        correoSede_jTextField.setEnabled(true);
        ciudadSede_jTextField.setEnabled(true);
        IdSede_jTextField.setEnabled(true);
        
        nombreSede_jTextField.setEditable(true);
        direccionSede_jTextField.setEditable(true);
        telefonoSede_jTextField.setEditable(true);
        correoSede_jTextField.setEditable(true);
        ciudadSede_jTextField.setEditable(true);
        IdSede_jTextField.setEditable(true);
        
        crearSede_jButton.setEnabled(true);
        cancelarSede_jButton.setEnabled(true);
        limpiarSede_jButton.setEnabled(true);
        //int idSede = consultasBD.cantidadSedes();
        //sedePrincipal.habilitarGestion(nombreSede_jTextField, direccionSede_jTextField, telefonoSede_jTextField, estadoSede_jComboBox, correoSede_jTextField, ciudadSede_jTextField, IdSede_jTextField, idSede);
    }//GEN-LAST:event_agregar_jButtonActionPerformed

    private void modificar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_jButtonActionPerformed
        nombreSede_jTextField.setEditable(true);
        direccionSede_jTextField.setEnabled(true);
        telefonoSede_jTextField.setEnabled(true);
        estadoSede_jComboBox.setEnabled(true);
        correoSede_jTextField.setEnabled(true);
        ciudadSede_jTextField.setEnabled(true);
        IdSede_jTextField.setEnabled(true);
        
        nombreSede_jTextField.setEnabled(false);
        direccionSede_jTextField.setEnabled(false);
        telefonoSede_jTextField.setEnabled(false);
        estadoSede_jComboBox.setEnabled(false);
        correoSede_jTextField.setEnabled(false);
        ciudadSede_jTextField.setEnabled(false);
        IdSede_jTextField.setEnabled(false);
        
        crearSede_jButton.setEnabled(true);
        cancelarSede_jButton.setEnabled(true);
        limpiarSede_jButton.setEnabled(true);
        
        //String id = JOptionPane.showInputDialog("Por favor ingrese el ID de la sede que desea modificar.");
        //consultasBD.datosParaModificarSede(id, nombreSede_jTextField, direccionSede_jTextField, telefonoSede_jTextField, estadoSede_jComboBox, correoSede_jTextField, ciudadSede_jTextField, IdSede_jTextField);
    }//GEN-LAST:event_modificar_jButtonActionPerformed

    private void nombreSede_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSede_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSede_jTextFieldActionPerformed

    private void listar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_jButtonActionPerformed
        listaSedes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_listar_jButtonActionPerformed

    private void estadoSede_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoSede_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoSede_jComboBoxActionPerformed

    private void ciudadSede_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadSede_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadSede_jTextFieldActionPerformed

    private void IdSede_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdSede_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdSede_jTextFieldActionPerformed

    private void crearSede_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSede_jButtonActionPerformed
        //Aqui van las funciones que agregan los datos de las sedes a la base de datos
        
        nombreSede_jTextField.setText("");
        direccionSede_jTextField.setText("");
        telefonoSede_jTextField.setText("");
        estadoSede_jComboBox.setSelectedIndex(0);
        correoSede_jTextField.setText("");
        ciudadSede_jTextField.setText("");
        IdSede_jTextField.setText("");
        
        nombreSede_jTextField.setEnabled(false);
        direccionSede_jTextField.setEnabled(false);
        telefonoSede_jTextField.setEnabled(false);
        estadoSede_jComboBox.setEnabled(false);
        correoSede_jTextField.setEnabled(false);
        ciudadSede_jTextField.setEnabled(false);
        IdSede_jTextField.setEnabled(false);
        
        crearSede_jButton.setEnabled(false);
        cancelarSede_jButton.setEnabled(false);
        limpiarSede_jButton.setEnabled(false);
    }//GEN-LAST:event_crearSede_jButtonActionPerformed

    private void cancelarSede_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarSede_jButtonActionPerformed
        nombreSede_jTextField.setText("");
        direccionSede_jTextField.setText("");
        telefonoSede_jTextField.setText("");
        estadoSede_jComboBox.setSelectedIndex(0);
        correoSede_jTextField.setText("");
        ciudadSede_jTextField.setText("");
        IdSede_jTextField.setText("");
        
        nombreSede_jTextField.setEnabled(false);
        direccionSede_jTextField.setEnabled(false);
        telefonoSede_jTextField.setEnabled(false);
        estadoSede_jComboBox.setEnabled(false);
        correoSede_jTextField.setEnabled(false);
        ciudadSede_jTextField.setEnabled(false);
        IdSede_jTextField.setEnabled(false);
        
        crearSede_jButton.setEnabled(false);
        cancelarSede_jButton.setEnabled(false);
        limpiarSede_jButton.setEnabled(false);
    }//GEN-LAST:event_cancelarSede_jButtonActionPerformed

    private void limpiarSede_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarSede_jButtonActionPerformed
        nombreSede_jTextField.setText("");
        direccionSede_jTextField.setText("");
        telefonoSede_jTextField.setText("");
        estadoSede_jComboBox.setSelectedIndex(0);
        correoSede_jTextField.setText("");
        ciudadSede_jTextField.setText("");
        IdSede_jTextField.setText("");
    }//GEN-LAST:event_limpiarSede_jButtonActionPerformed
    
    public JButton getAceptar_jButton(){
        return crearSede_jButton;
    }
    
    public JButton getCancelar_jButton(){
        return cancelarSede_jButton;
    }
    
    public JButton getLimpiar_jButton(){
        return limpiarSede_jButton;
    }
    
    public JTextField getNombre_jTextField(){
        return nombreSede_jTextField;
    }
    
    public JTextField getDireccion_jTextField(){
        return direccionSede_jTextField;
    }
    
    public JTextField getTelefono_jTextField(){
        return telefonoSede_jTextField;
    }
    
    public JComboBox getEstado_jComboBox(){
        return estadoSede_jComboBox;
    }
    
    public JTextField getEmail_jTextField(){
        return correoSede_jTextField;
    }
    
    public JTextField getCiudad_jComboBox(){
        return ciudadSede_jTextField;
    }
    
    public JTextField getIdSede_jComboBox(){
        return IdSede_jTextField;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EstadoSede_jLabel;
    private javax.swing.JLabel IdSede_jLabel;
    private javax.swing.JTextField IdSede_jTextField;
    private javax.swing.JButton agregar_jButton;
    private javax.swing.JButton cancelarSede_jButton;
    private javax.swing.JLabel ciudadSede_jLabel;
    private javax.swing.JTextField ciudadSede_jTextField;
    private javax.swing.JLabel correoSede_jLabel;
    private javax.swing.JTextField correoSede_jTextField;
    private javax.swing.JButton crearSede_jButton;
    private javax.swing.JLabel direccionSede_jLabel;
    private javax.swing.JTextField direccionSede_jTextField;
    private javax.swing.JComboBox estadoSede_jComboBox;
    private javax.swing.JPanel gestion_jPanel;
    private javax.swing.JLabel iconoSedes_jLabel;
    private javax.swing.JLabel icono_jLabel;
    private javax.swing.JPanel info_jPanel;
    private javax.swing.JButton limpiarSede_jButton;
    private javax.swing.JButton listar_jButton;
    private javax.swing.JButton menu_jButton;
    private javax.swing.JButton modificar_jButton;
    private javax.swing.JLabel nombreSede_jLabel;
    private javax.swing.JTextField nombreSede_jTextField;
    private javax.swing.JPanel opcionSedes_jPanel;
    private javax.swing.JPanel ppal_jPanel;
    private javax.swing.JButton salir_jButton;
    private javax.swing.JLabel sedes_jLabel;
    private javax.swing.JLabel telefonoSede_jLabel;
    private javax.swing.JTextField telefonoSede_jTextField;
    // End of variables declaration//GEN-END:variables
}
