package GUI;



import Base_de_Datos.ConsultarDatos;
import Base_de_Datos.IngresarDatos;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DanielFelipe
 */
public class gestion_usuarios extends javax.swing.JFrame {
    
    private menu menu;
    private Listar_usuarios listaUsuarios;
    
    
    public gestion_usuarios(menu menu) {
        
        
        listaUsuarios = new Listar_usuarios(this);
        
        
        initComponents();
        
        this.menu = menu;
        
        nombre_jTextField.setEnabled(false);
        apellido_jTextField.setEnabled(false);
        cedula_jTextField.setEnabled(false);
        nacimiento_jTextField.setEnabled(false);
        telefono_jTextField.setEnabled(false);
        direccion_jTextField.setEnabled(false);
        email_jTextField.setEnabled(false);
        cargo_jComboBox.setEnabled(false);
        estado_jComboBox.setEnabled(false);
        idSede_jComboBox.setEnabled(false);
        contraseña_jTextField.setEnabled(false);
        aceptar_jButton.setEnabled(false);
        cancelar_jButton.setEnabled(false);
        limpiar_jButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info_jPanel = new javax.swing.JPanel();
        icono_jLabel = new javax.swing.JLabel();
        usuarios_jLabel = new javax.swing.JLabel();
        ppal_jPanel = new javax.swing.JPanel();
        salir_jButton = new javax.swing.JButton();
        menu_jButton = new javax.swing.JButton();
        opcionUsuarios_jPanel = new javax.swing.JPanel();
        agregar_jButton = new javax.swing.JButton();
        modificar_jButton = new javax.swing.JButton();
        listar_jButton = new javax.swing.JButton();
        gestion_jPanel = new javax.swing.JPanel();

        nombre_jLabel = new javax.swing.JLabel();
        apellido_jLabel = new javax.swing.JLabel();
        apellido_jTextField = new javax.swing.JTextField();
        apellido_jTextField.setEditable(false);
        cedula_jLabel = new javax.swing.JLabel();
        cedula_jTextField = new javax.swing.JTextField();
        nacimiento_jLabel = new javax.swing.JLabel();
        telefono_jLabel = new javax.swing.JLabel();
        telefono_jTextField = new javax.swing.JTextField();
        direccion_jLabel = new javax.swing.JLabel();
        direccion_jTextField = new javax.swing.JTextField();
        cargo_jLabel = new javax.swing.JLabel();
        email_jTextField = new javax.swing.JTextField();
        email_jLabel1 = new javax.swing.JLabel();
        estado_jLabel = new javax.swing.JLabel();
        idSede_jLabel = new javax.swing.JLabel();
        contraseña_jLabel = new javax.swing.JLabel();
        nacimiento_jTextField = new javax.swing.JTextField();
        contraseña_jTextField = new javax.swing.JTextField();
        cargo_jComboBox = new javax.swing.JComboBox();
        estado_jComboBox = new javax.swing.JComboBox();
        idSede_jComboBox = new javax.swing.JComboBox();
        nombre_jTextField = new javax.swing.JTextField();
        apellido_jTextField.setEditable(false);
        iconoUsuarios_jLabel = new javax.swing.JLabel();
        aceptar_jButton = new javax.swing.JButton();
        cancelar_jButton = new javax.swing.JButton();
        limpiar_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(698, 432));

        icono_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icono.png"))); // NOI18N
        icono_jLabel.setText("jLabel1");

        usuarios_jLabel.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        usuarios_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarios_jLabel.setText("Módulo de gestión de usuarios");

        javax.swing.GroupLayout info_jPanelLayout = new javax.swing.GroupLayout(info_jPanel);
        info_jPanel.setLayout(info_jPanelLayout);
        info_jPanelLayout.setHorizontalGroup(
            info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_jPanelLayout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(icono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(info_jPanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(usuarios_jLabel)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );
        info_jPanelLayout.setVerticalGroup(
            info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(icono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(info_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(info_jPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(usuarios_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        salir_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/16-em-cross.png"))); // NOI18N
        salir_jButton.setText("Salir");
        salir_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_jButtonActionPerformed(evt);
            }
        });

        menu_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-frame.png"))); // NOI18N
        menu_jButton.setText("Menú");
        menu_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ppal_jPanelLayout = new javax.swing.GroupLayout(ppal_jPanel);
        ppal_jPanel.setLayout(ppal_jPanelLayout);
        ppal_jPanelLayout.setHorizontalGroup(
            ppal_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppal_jPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(menu_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir_jButton))
        );
        ppal_jPanelLayout.setVerticalGroup(
            ppal_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppal_jPanelLayout.createSequentialGroup()
                .addGroup(ppal_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir_jButton)
                    .addComponent(menu_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        agregar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-image-add.png"))); // NOI18N
        agregar_jButton.setText("Agregar");
        agregar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_jButtonActionPerformed(evt);
            }
        });

        modificar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-image-open.png"))); // NOI18N
        modificar_jButton.setText("Modificar");
        modificar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_jButtonActionPerformed(evt);
            }
        });

        listar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-sidebar.png"))); // NOI18N
        listar_jButton.setText("Listar");
        listar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionUsuarios_jPanelLayout = new javax.swing.GroupLayout(opcionUsuarios_jPanel);
        opcionUsuarios_jPanel.setLayout(opcionUsuarios_jPanelLayout);
        opcionUsuarios_jPanelLayout.setHorizontalGroup(
            opcionUsuarios_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionUsuarios_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agregar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listar_jButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        opcionUsuarios_jPanelLayout.setVerticalGroup(
            opcionUsuarios_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionUsuarios_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(modificar_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(opcionUsuarios_jPanelLayout.createSequentialGroup()
                .addComponent(listar_jButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gestion_jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Usuario"));

        nombre_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        nombre_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombre_jLabel.setText("Nombre*");

        apellido_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        apellido_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apellido_jLabel.setText("Apellidos*");

        cedula_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        cedula_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cedula_jLabel.setText("Cédula*");

        cedula_jTextField.setEditable(false);

        nacimiento_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        nacimiento_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nacimiento_jLabel.setText("Fecha Nac.*");

        telefono_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        telefono_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telefono_jLabel.setText("Telefono*");

        telefono_jTextField.setEditable(false);

        direccion_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        direccion_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        direccion_jLabel.setText("Dirección");

        direccion_jTextField.setEditable(false);
        direccion_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_jTextFieldActionPerformed(evt);
            }
        });

        cargo_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        cargo_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cargo_jLabel.setText("Cargo");

        email_jTextField.setEditable(false);
        email_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_jTextFieldActionPerformed(evt);
            }
        });

        email_jLabel1.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        email_jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        email_jLabel1.setText("e-mail");

        estado_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        estado_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estado_jLabel.setText("Estado");

        idSede_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        idSede_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idSede_jLabel.setText("ID-Sede");

        contraseña_jLabel.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        contraseña_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contraseña_jLabel.setText("Contraseña");

        cedula_jTextField.setEditable(false);

        email_jTextField.setEditable(false);
        contraseña_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña_jTextFieldActionPerformed(evt);
            }
        });

        cargo_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Administrador", "Gerente", "Contador", "Operario de oficina", "Secretaria", "Auxiliar de operación" }));

        estado_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Activo", "Inactivo" }));

        idSede_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        javax.swing.GroupLayout gestion_jPanelLayout = new javax.swing.GroupLayout(gestion_jPanel);
        gestion_jPanel.setLayout(gestion_jPanelLayout);
        gestion_jPanelLayout.setHorizontalGroup(
            gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestion_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(nombre_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(apellido_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellido_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(cedula_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedula_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(nacimiento_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nacimiento_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(telefono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(direccion_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccion_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(email_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createSequentialGroup()
                        .addComponent(contraseña_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contraseña_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gestion_jPanelLayout.createSequentialGroup()
                            .addComponent(idSede_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idSede_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gestion_jPanelLayout.createSequentialGroup()
                            .addComponent(estado_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(estado_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gestion_jPanelLayout.createSequentialGroup()
                            .addComponent(cargo_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cargo_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        gestion_jPanelLayout.setVerticalGroup(
            gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestion_jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_jLabel)
                    .addComponent(nombre_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido_jLabel)
                    .addComponent(apellido_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedula_jLabel)
                    .addComponent(cedula_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacimiento_jLabel)
                    .addComponent(nacimiento_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono_jLabel)
                    .addComponent(telefono_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion_jLabel)
                    .addComponent(direccion_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargo_jLabel)
                    .addComponent(cargo_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado_jLabel)
                    .addComponent(estado_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idSede_jLabel)
                    .addComponent(idSede_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gestion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña_jLabel)
                    .addComponent(contraseña_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iconoUsuarios_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/usuarios.jpg"))); // NOI18N

        aceptar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/16-em-check.png"))); // NOI18N
        aceptar_jButton.setText("Aceptar");
        aceptar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_jButtonActionPerformed(evt);
            }
        });

        cancelar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/12-em-cross.png"))); // NOI18N
        cancelar_jButton.setText("Cancelar");
        cancelar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_jButtonActionPerformed(evt);
            }
        });

        limpiar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/16-broom_opt.png"))); // NOI18N
        limpiar_jButton.setText("Limpiar");
        limpiar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(opcionUsuarios_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ppal_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(gestion_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iconoUsuarios_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aceptar_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(limpiar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ppal_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionUsuarios_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gestion_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(iconoUsuarios_jLabel)
                        .addGap(18, 18, 18)
                        .addComponent(aceptar_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiar_jButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jButtonActionPerformed
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menu_jButtonActionPerformed

    private void salir_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_jButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_jButtonActionPerformed

    private void agregar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_jButtonActionPerformed
        nombre_jTextField.setEditable(true);
        apellido_jTextField.setEditable(true);
        cedula_jTextField.setEditable(true);
        nacimiento_jTextField.setEditable(true);
        telefono_jTextField.setEditable(true);
        direccion_jTextField.setEditable(true);
        email_jTextField.setEditable(true);
        contraseña_jTextField.setEditable(true);
        
        nombre_jTextField.setEnabled(true);
        apellido_jTextField.setEnabled(true);
        cedula_jTextField.setEnabled(true);
        nacimiento_jTextField.setEnabled(true);
        telefono_jTextField.setEnabled(true);
        direccion_jTextField.setEnabled(true);
        email_jTextField.setEnabled(true);
        cargo_jComboBox.setEnabled(true);
        estado_jComboBox.setEnabled(true);
        idSede_jComboBox.setEnabled(true);
        contraseña_jTextField.setEnabled(true);
        aceptar_jButton.setEnabled(true);
        cancelar_jButton.setEnabled(true);
        limpiar_jButton.setEnabled(true);
    }//GEN-LAST:event_agregar_jButtonActionPerformed

    private void modificar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_jButtonActionPerformed
        nombre_jTextField.setEditable(true);
        apellido_jTextField.setEditable(true);
        cedula_jTextField.setEditable(true);
        nacimiento_jTextField.setEditable(true);
        telefono_jTextField.setEditable(true);
        direccion_jTextField.setEditable(true);
        email_jTextField.setEditable(true);
        contraseña_jTextField.setEditable(true);
        
        nombre_jTextField.setEnabled(true);
        apellido_jTextField.setEnabled(true);
        cedula_jTextField.setEnabled(true);
        nacimiento_jTextField.setEnabled(true);
        telefono_jTextField.setEnabled(true);
        direccion_jTextField.setEnabled(true);
        email_jTextField.setEnabled(true);
        cargo_jComboBox.setEnabled(true);
        estado_jComboBox.setEnabled(true);
        idSede_jComboBox.setEnabled(true);
        contraseña_jTextField.setEnabled(true);
        aceptar_jButton.setEnabled(true);
        cancelar_jButton.setEnabled(true);
        limpiar_jButton.setEnabled(true);
    }//GEN-LAST:event_modificar_jButtonActionPerformed

    private void listar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_jButtonActionPerformed
        listaUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_listar_jButtonActionPerformed

    private void direccion_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_jTextFieldActionPerformed

    private void email_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_jTextFieldActionPerformed

    private void aceptar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_jButtonActionPerformed
        //Aqui van las funciones que agregan los datos a la base de datos
        
        nombre_jTextField.setText("");
        apellido_jTextField.setText("");
        cedula_jTextField.setText("");
        nacimiento_jTextField.setText("");
        telefono_jTextField.setText("");
        direccion_jTextField.setText("");
        email_jTextField.setText("");
        cargo_jComboBox.setSelectedIndex(0);
        estado_jComboBox.setSelectedIndex(0);
        idSede_jComboBox.setSelectedIndex(0);
        contraseña_jTextField.setText("");
        
        nombre_jTextField.setEnabled(false);
        apellido_jTextField.setEnabled(false);
        cedula_jTextField.setEnabled(false);
        nacimiento_jTextField.setEnabled(false);
        telefono_jTextField.setEnabled(false);
        direccion_jTextField.setEnabled(false);
        email_jTextField.setEnabled(false);
        cargo_jComboBox.setEnabled(false);
        estado_jComboBox.setEnabled(false);
        idSede_jComboBox.setEnabled(false);
        contraseña_jTextField.setEnabled(false);
        aceptar_jButton.setEnabled(false);
        cancelar_jButton.setEnabled(false);
        limpiar_jButton.setEnabled(false);
    }//GEN-LAST:event_aceptar_jButtonActionPerformed

    private void cancelar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_jButtonActionPerformed
        nombre_jTextField.setText("");
        apellido_jTextField.setText("");
        cedula_jTextField.setText("");
        nacimiento_jTextField.setText("");
        telefono_jTextField.setText("");
        direccion_jTextField.setText("");
        email_jTextField.setText("");
        cargo_jComboBox.setSelectedIndex(0);
        estado_jComboBox.setSelectedIndex(0);
        idSede_jComboBox.setSelectedIndex(0);
        contraseña_jTextField.setText("");
        
        nombre_jTextField.setEnabled(false);
        apellido_jTextField.setEnabled(false);
        cedula_jTextField.setEnabled(false);
        nacimiento_jTextField.setEnabled(false);
        telefono_jTextField.setEnabled(false);
        direccion_jTextField.setEnabled(false);
        email_jTextField.setEnabled(false);
        cargo_jComboBox.setEnabled(false);
        estado_jComboBox.setEnabled(false);
        idSede_jComboBox.setEnabled(false);
        contraseña_jTextField.setEnabled(false);
        aceptar_jButton.setEnabled(false);
        cancelar_jButton.setEnabled(false);
        limpiar_jButton.setEnabled(false);
    }//GEN-LAST:event_cancelar_jButtonActionPerformed

    private void limpiar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_jButtonActionPerformed
        nombre_jTextField.setText("");
        apellido_jTextField.setText("");
        cedula_jTextField.setText("");
        nacimiento_jTextField.setText("");
        telefono_jTextField.setText("");
        direccion_jTextField.setText("");
        email_jTextField.setText("");
        cargo_jComboBox.setSelectedIndex(0);
        estado_jComboBox.setSelectedIndex(0);
        idSede_jComboBox.setSelectedIndex(0);
        contraseña_jTextField.setText("");
    }//GEN-LAST:event_limpiar_jButtonActionPerformed

    private void contraseña_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña_jTextFieldActionPerformed
        
    }//GEN-LAST:event_contraseña_jTextFieldActionPerformed

    public JButton getAceptar_jButton(){
        return aceptar_jButton;
    }
    
    public JButton getCancelar_jButton(){
        return cancelar_jButton;
    }
    
    public JButton getLimpiar_jButton(){
        return limpiar_jButton;
    }
    
    public JTextField getNombre_jTextField(){
        return nombre_jTextField;
    }
    
    public JTextField getApellido_jTextField(){
        return apellido_jTextField;
    }
    
    public JTextField getCedula_jTextField(){
        return cedula_jTextField;
    }
    
    public JTextField getNacimiento_jTextField(){
        return nacimiento_jTextField;
    }
    
    public JTextField getTelefono_jTextField(){
        return telefono_jTextField;
    }
    
    public JTextField getDireccion_jTextField(){
        return direccion_jTextField;
    }
    
    public JTextField getEmail_jTextField(){
        return email_jTextField;
    }
    
    public JComboBox getCargo_jComboBox(){
        return cargo_jComboBox;
    }
    
    public JComboBox getEstado_jComboBox(){
        return estado_jComboBox;
    }
    
    public JComboBox getIdSede_jComboBox(){
        return idSede_jComboBox;
    }
    
    public JTextField getContraseña_jTextField(){
        return contraseña_jTextField;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_jButton;
    private javax.swing.JButton agregar_jButton;
    private javax.swing.JLabel apellido_jLabel;
    private javax.swing.JTextField apellido_jTextField;
    private javax.swing.JButton cancelar_jButton;
    private javax.swing.JComboBox cargo_jComboBox;
    private javax.swing.JLabel cargo_jLabel;
    private javax.swing.JLabel cedula_jLabel;
    private javax.swing.JTextField cedula_jTextField;
    private javax.swing.JLabel contraseña_jLabel;
    private javax.swing.JTextField contraseña_jTextField;
    private javax.swing.JLabel direccion_jLabel;
    private javax.swing.JTextField direccion_jTextField;
    private javax.swing.JLabel email_jLabel1;
    private javax.swing.JTextField email_jTextField;
    private javax.swing.JComboBox estado_jComboBox;
    private javax.swing.JLabel estado_jLabel;
    private javax.swing.JPanel gestion_jPanel;
    private javax.swing.JLabel iconoUsuarios_jLabel;
    private javax.swing.JLabel icono_jLabel;
    private javax.swing.JComboBox idSede_jComboBox;
    private javax.swing.JLabel idSede_jLabel;
    private javax.swing.JPanel info_jPanel;
    private javax.swing.JButton limpiar_jButton;
    private javax.swing.JButton listar_jButton;
    private javax.swing.JButton menu_jButton;
    private javax.swing.JButton modificar_jButton;
    private javax.swing.JLabel nacimiento_jLabel;
    private javax.swing.JTextField nacimiento_jTextField;
    private javax.swing.JLabel nombre_jLabel;
    private javax.swing.JTextField nombre_jTextField;
    private javax.swing.JPanel opcionUsuarios_jPanel;
    private javax.swing.JPanel ppal_jPanel;
    private javax.swing.JButton salir_jButton;
    private javax.swing.JLabel telefono_jLabel;
    private javax.swing.JTextField telefono_jTextField;
    private javax.swing.JLabel usuarios_jLabel;
    // End of variables declaration//GEN-END:variables
}
