/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.gestion_usuarios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanielFelipe
 */
public class Listar_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form gestion
     */
    
    gestion_usuarios usuarios;
    public Listar_usuarios() {
        initComponents();
        usuarios = new gestion_usuarios();
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableListarUsuarios.getModel();
        modeloTabla.addRow(new Object[]{"Daniel", "1", "2", "3", "4", "5", "6", "Administrador", "Activo", "7"});
        modeloTabla.addRow(new Object[]{"Marcelo", "1", "2", "3", "4", "5", "6", "Gerente", "Inactivo", "7"});
        modeloTabla.addRow(new Object[]{"Matias", "1", "2", "3", "4", "5", "6", "Algo", "Inactivo", "7"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListarUsuarios = new javax.swing.JPanel();
        jScrollPaneListarUsuarios = new javax.swing.JScrollPane();
        jTableListarUsuarios = new javax.swing.JTable();
        Volver_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelListarUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));

        jTableListarUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Cédula", "Fecha de Nacimiento", "Teléfono", "Dirección", "e-mail", "Cargo", "Estado", "Código Sede"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarUsuariosMouseClicked(evt);
            }
        });
        jScrollPaneListarUsuarios.setViewportView(jTableListarUsuarios);

        Volver_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/24-frame.png"))); // NOI18N
        Volver_jButton.setText("Volver");
        Volver_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarUsuariosLayout = new javax.swing.GroupLayout(jPanelListarUsuarios);
        jPanelListarUsuarios.setLayout(jPanelListarUsuariosLayout);
        jPanelListarUsuariosLayout.setHorizontalGroup(
            jPanelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver_jButton)
                .addGap(346, 346, 346))
        );
        jPanelListarUsuariosLayout.setVerticalGroup(
            jPanelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarUsuariosLayout.createSequentialGroup()
                .addComponent(jScrollPaneListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Volver_jButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver_jButtonActionPerformed
        usuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Volver_jButtonActionPerformed

    private void jTableListarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarUsuariosMouseClicked
        int filaseleccionada;

        try{

            filaseleccionada = jTableListarUsuarios.getSelectedRow();

            DefaultTableModel modelotabla = (DefaultTableModel) jTableListarUsuarios.getModel();

            String nombres = (String) modelotabla.getValueAt(filaseleccionada, 0);
            String apellidos = (String) modelotabla.getValueAt(filaseleccionada, 1);
            String cedula = (String) modelotabla.getValueAt(filaseleccionada, 2);
            String fecha = (String) modelotabla.getValueAt(filaseleccionada, 3);
            String telefono = (String) modelotabla.getValueAt(filaseleccionada, 4);
            String direccion = (String) modelotabla.getValueAt(filaseleccionada, 5);
            String eMail = (String) modelotabla.getValueAt(filaseleccionada, 6);
            String cargo = (String) modelotabla.getValueAt(filaseleccionada, 7);
            String estado = (String) modelotabla.getValueAt(filaseleccionada, 8);
            //String codSede = (String) modelotabla.getValueAt(filaseleccionada, 9);

            usuarios.getNombre_jTextField().setText(nombres);
            usuarios.getApellido_jTextField().setText(apellidos);
            usuarios.getCedula_jTextField().setText(cedula);
            usuarios.getNacimiento_jTextField().setText(fecha);
            usuarios.getTelefono_jTextField().setText(telefono);
            usuarios.getDireccion_jTextField().setText(direccion);
            usuarios.getEmail_jTextField().setText(eMail);
            usuarios.getCargo_jComboBox().setSelectedItem(cargo);
            usuarios.getEstado_jComboBox().setSelectedItem(estado);
            //usuarios.getIdSede_jComboBox().setText(codSede);
            
            usuarios.getNombre_jTextField().setEnabled(true);
            usuarios.getApellido_jTextField().setEnabled(true);
            usuarios.getCedula_jTextField().setEnabled(true);
            usuarios.getNacimiento_jTextField().setEnabled(true);
            usuarios.getTelefono_jTextField().setEnabled(true);
            usuarios.getDireccion_jTextField().setEnabled(true);
            usuarios.getEmail_jTextField().setEnabled(true);
            usuarios.getCargo_jComboBox().setEnabled(true);
            usuarios.getEstado_jComboBox().setEnabled(true);
            usuarios.getIdSede_jComboBox().setEnabled(true);
            usuarios.getContraseña_jTextField().setEnabled(true);
            
            usuarios.getNombre_jTextField().setEditable(true);
            usuarios.getApellido_jTextField().setEditable(true);
            usuarios.getCedula_jTextField().setEditable(true);
            usuarios.getNacimiento_jTextField().setEditable(true);
            usuarios.getTelefono_jTextField().setEditable(true);
            usuarios.getDireccion_jTextField().setEditable(true);
            usuarios.getEmail_jTextField().setEditable(true);
            usuarios.getContraseña_jTextField().setEditable(true);
            
            usuarios.getAceptar_jButton().setEnabled(true);
            usuarios.getCancelar_jButton().setEnabled(true);
            usuarios.getLimpiar_jButton().setEnabled(true);
            
            usuarios.setVisible(true);
            this.setVisible(false);

        } catch (Exception ex) {}
    }//GEN-LAST:event_jTableListarUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver_jButton;
    private javax.swing.JPanel jPanelListarUsuarios;
    private javax.swing.JScrollPane jScrollPaneListarUsuarios;
    private javax.swing.JTable jTableListarUsuarios;
    // End of variables declaration//GEN-END:variables
}
