/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Base_de_Datos.LoginSQL;

//----------------------------------------------------------
public class login extends javax.swing.JPanel {
    
    private LoginSQL log;

    /**
     * Creates new form login
     */
    
    private String usuario;
    private String password;
    
    
    
    public login() {
        initComponents();
        log = new LoginSQL();
    }
    
    //-------------Setters-------------

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    
    //-----------Getters---------------------

    public String getUsuario() {
        return usuario;
    }

    public String getPassword() {
        return password;
    }
    
    //---------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo_label = new javax.swing.JLabel();
        exit_button = new javax.swing.JButton();
        entrar_button = new javax.swing.JButton();
        usuario_label = new javax.swing.JLabel();
        usuario_jTextField = new javax.swing.JTextField();
        contraseña_label = new javax.swing.JLabel();
        diseñado_label = new javax.swing.JLabel();
        contraseña_jPasswordField1 = new javax.swing.JPasswordField();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(600, 300));

        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/logo.png"))); // NOI18N

        exit_button.setText("Salir");

        entrar_button.setText("Entrar");
        entrar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar_buttonActionPerformed(evt);
            }
        });

        usuario_label.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        usuario_label.setText("Usuario:");

        usuario_jTextField.setText("jTextField1");

        contraseña_label.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        contraseña_label.setText("Contraseña:");

        diseñado_label.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        diseñado_label.setText("Powered by: X");

        contraseña_jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diseñado_label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(entrar_button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuario_label)
                                    .addComponent(contraseña_label))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuario_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(contraseña_jPasswordField1))))
                        .addGap(18, 18, 18)
                        .addComponent(logo_label)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diseñado_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuario_label)
                            .addComponent(usuario_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contraseña_label)
                            .addComponent(contraseña_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exit_button)
                            .addComponent(entrar_button))))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entrar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrar_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña_jPasswordField1;
    private javax.swing.JLabel contraseña_label;
    private javax.swing.JLabel diseñado_label;
    private javax.swing.JButton entrar_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel logo_label;
    private javax.swing.JTextField usuario_jTextField;
    private javax.swing.JLabel usuario_label;
    // End of variables declaration//GEN-END:variables
}
