/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author neox
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    gestion_usuarios usuarios;
    //Listar_usuarios listar_usuario;
    gestion_sedes sedes;
    
    public menu() {
        initComponents();
        sedes = new gestion_sedes(this);
        usuarios = new gestion_usuarios(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado_jPanel = new javax.swing.JPanel();
        programa_jLabel1 = new javax.swing.JLabel();
        icono_jLabel = new javax.swing.JLabel();
        menu_jPanel = new javax.swing.JPanel();
        gSedes_jButton = new javax.swing.JButton();
        gSedes_jLabel = new javax.swing.JLabel();
        gUsuarios_jButton = new javax.swing.JButton();
        gUsuarios_jLabel = new javax.swing.JLabel();
        nomina_jButton = new javax.swing.JButton();
        nomina_jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion_jTextArea = new javax.swing.JTextArea();
        descripcion_jTextArea.enable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        programa_jLabel1.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        programa_jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programa_jLabel1.setText("Nombre del Programa");

        icono_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icono.png"))); // NOI18N
        icono_jLabel.setText("jLabel1");

        javax.swing.GroupLayout encabezado_jPanelLayout = new javax.swing.GroupLayout(encabezado_jPanel);
        encabezado_jPanel.setLayout(encabezado_jPanelLayout);
        encabezado_jPanelLayout.setHorizontalGroup(
            encabezado_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezado_jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(programa_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        encabezado_jPanelLayout.setVerticalGroup(
            encabezado_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezado_jPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(encabezado_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programa_jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icono_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        gSedes_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/sedes.jpg"))); // NOI18N
        gSedes_jButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                gSedes_jButtonMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gSedes_jButtonMouseMoved(evt);
            }
        });
        gSedes_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gSedes_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gSedes_jButtonMouseExited(evt);
            }
        });
        gSedes_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSedes_jButtonActionPerformed(evt);
            }
        });

        gSedes_jLabel.setFont(new java.awt.Font("Kalinga", 0, 11)); // NOI18N
        gSedes_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gSedes_jLabel.setText("Gestión de Sedes");

        gUsuarios_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/usuarios.jpg"))); // NOI18N
        gUsuarios_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gUsuarios_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gUsuarios_jButtonMouseExited(evt);
            }
        });
        gUsuarios_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gUsuarios_jButtonActionPerformed(evt);
            }
        });

        gUsuarios_jLabel.setFont(new java.awt.Font("Kalinga", 0, 11)); // NOI18N
        gUsuarios_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gUsuarios_jLabel.setText("Gestión de Usuarios");

        nomina_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/pos.jpg"))); // NOI18N
        nomina_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomina_jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nomina_jButtonMouseExited(evt);
            }
        });
        nomina_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomina_jButtonActionPerformed(evt);
            }
        });

        nomina_jLabel.setFont(new java.awt.Font("Kalinga", 0, 11)); // NOI18N
        nomina_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomina_jLabel.setText("Nomina");

        descripcion_jTextArea.setColumns(20);
        descripcion_jTextArea.setRows(5);
        jScrollPane1.setViewportView(descripcion_jTextArea);

        javax.swing.GroupLayout menu_jPanelLayout = new javax.swing.GroupLayout(menu_jPanel);
        menu_jPanel.setLayout(menu_jPanelLayout);
        menu_jPanelLayout.setHorizontalGroup(
            menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_jPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_jPanelLayout.createSequentialGroup()
                        .addGroup(menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gSedes_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gSedes_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gUsuarios_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gUsuarios_jLabel))
                        .addGap(89, 89, 89)
                        .addGroup(menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomina_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomina_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        menu_jPanelLayout.setVerticalGroup(
            menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_jPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(menu_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menu_jPanelLayout.createSequentialGroup()
                        .addComponent(gSedes_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gSedes_jLabel))
                    .addGroup(menu_jPanelLayout.createSequentialGroup()
                        .addComponent(nomina_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomina_jLabel))
                    .addGroup(menu_jPanelLayout.createSequentialGroup()
                        .addComponent(gUsuarios_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gUsuarios_jLabel)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(encabezado_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(encabezado_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(menu_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gUsuarios_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gUsuarios_jButtonActionPerformed
        usuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gUsuarios_jButtonActionPerformed

    private void nomina_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomina_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomina_jButtonActionPerformed

    private void gSedes_jButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gSedes_jButtonMouseMoved

    }//GEN-LAST:event_gSedes_jButtonMouseMoved

    private void gSedes_jButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gSedes_jButtonMouseDragged
        
    }//GEN-LAST:event_gSedes_jButtonMouseDragged

    private void gSedes_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gSedes_jButtonMouseEntered
        descripcion_jTextArea.setText("Modulo de gestion de Usuarios \n Añadir, Eliminar y Modificar Usuarios");
    }//GEN-LAST:event_gSedes_jButtonMouseEntered

    private void gSedes_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gSedes_jButtonMouseExited
        descripcion_jTextArea.setText("");
    }//GEN-LAST:event_gSedes_jButtonMouseExited

    private void gUsuarios_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gUsuarios_jButtonMouseEntered
        descripcion_jTextArea.setText("Modulo de gestion de Sedes \n Añadir, Eliminar y Modificar Sedes");
    }//GEN-LAST:event_gUsuarios_jButtonMouseEntered

    private void gUsuarios_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gUsuarios_jButtonMouseExited
        descripcion_jTextArea.setText("");
    }//GEN-LAST:event_gUsuarios_jButtonMouseExited

    private void nomina_jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomina_jButtonMouseEntered
        descripcion_jTextArea.setText("Modulo de Nomina \n Permite al usuario gestionar la Nomina de la compañia");
    }//GEN-LAST:event_nomina_jButtonMouseEntered

    private void nomina_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomina_jButtonMouseExited
        descripcion_jTextArea.setText("");
    }//GEN-LAST:event_nomina_jButtonMouseExited

    private void gSedes_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSedes_jButtonActionPerformed
        sedes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gSedes_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripcion_jTextArea;
    private javax.swing.JPanel encabezado_jPanel;
    private javax.swing.JButton gSedes_jButton;
    private javax.swing.JLabel gSedes_jLabel;
    private javax.swing.JButton gUsuarios_jButton;
    private javax.swing.JLabel gUsuarios_jLabel;
    private javax.swing.JLabel icono_jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu_jPanel;
    private javax.swing.JButton nomina_jButton;
    private javax.swing.JLabel nomina_jLabel;
    private javax.swing.JLabel programa_jLabel1;
    // End of variables declaration//GEN-END:variables
}
